#!/usr/bin/env bash
# maintenance-report.sh — report-only daily maintenance digest.
#
# This is the CI-safe, READ-ONLY counterpart of the `/maintain` Claude Code
# skill (`.claude/commands/maintain.md`). The skill takes *actions* (commits
# fixes, labels issues, recreates AVDs); running it unattended in CI is unsafe.
# Instead, this script reproduces the *observable* signals of the skill's
# 12-section sweep — CI health, open issues/PRs, dependency drift, version
# sync, quality signals, release decision — as a single structured Markdown
# report.
#
# The report is printed to stdout AND, when running inside GitHub Actions,
# appended to $GITHUB_STEP_SUMMARY. `maintenance.yml` additionally posts it to
# a single auto-updated tracking issue so the digest is browsable day to day.
#
# Design rules:
#   - READ-ONLY: never commits, never labels, never deletes. Pure observation.
#   - NON-BLOCKING: every probe is wrapped so a transient failure degrades the
#     row to "unknown" instead of failing the workflow. Exit code is always 0.
#   - ROBUST: network probes retry a few times before giving up.
#
# Usage:
#   bash .claude/scripts/maintenance-report.sh            # print report
#   bash .claude/scripts/maintenance-report.sh -o out.md  # also write to file
#
# Requires: bash, curl, jq. `gh` is optional — rows that need it degrade
# gracefully to "unknown" when it is absent or unauthenticated.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$REPO_ROOT" || { echo "Cannot cd to repo root" >&2; exit 1; }

OUT_FILE=""
while [ $# -gt 0 ]; do
  case "$1" in
    -o|--output) OUT_FILE="${2:-}"; shift 2 ;;
    *) echo "Unknown argument: $1" >&2; exit 2 ;;
  esac
done

TODAY="$(date -u +%Y-%m-%d)"
REPO_SLUG="${GITHUB_REPOSITORY:-sceneview/sceneview}"

# ── helpers ────────────────────────────────────────────────────────────────

# curl with retry/backoff — transient API failures must not abort the report.
fetch() {
  local url="$1" attempt
  for attempt in 1 2 3; do
    if curl -sf --max-time 20 "$url" 2>/dev/null; then
      return 0
    fi
    sleep $((attempt * 2))
  done
  return 1
}

# Is `gh` usable (installed AND authenticated)?
gh_ready() {
  command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1
}

# Run a gh command with retry; echo empty string on persistent failure.
gh_try() {
  local attempt out
  for attempt in 1 2 3; do
    if out="$(gh "$@" 2>/dev/null)"; then
      printf '%s' "$out"
      return 0
    fi
    sleep $((attempt * 2))
  done
  printf ''
  return 1
}

# Accumulate the report in a variable so we can emit it to several sinks.
REPORT=""
add() { REPORT+="$1"$'\n'; }

# ── header ─────────────────────────────────────────────────────────────────

add "## SceneView daily maintenance digest — ${TODAY}"
add ""
add "_Report-only sweep generated by \`.claude/scripts/maintenance-report.sh\`._"
add "_This is the CI-safe mirror of the \`/maintain\` skill — it observes, it never acts._"
add ""
add "| Area | Status | Notes |"
add "|---|---|---|"

# ── 1. CI & build health ───────────────────────────────────────────────────

CI_STATUS="unknown"; CI_NOTES="gh unavailable"
if gh_ready; then
  CI_JSON="$(gh_try run list --repo "$REPO_SLUG" --workflow=ci.yml --limit 7 \
    --json conclusion,name 2>/dev/null)"
  if [ -n "$CI_JSON" ]; then
    CI_FAILS="$(printf '%s' "$CI_JSON" | jq '[.[] | select(.conclusion == "failure")] | length' 2>/dev/null || echo "?")"
    CI_TOTAL="$(printf '%s' "$CI_JSON" | jq 'length' 2>/dev/null || echo "?")"
    if [ "$CI_FAILS" = "0" ]; then
      CI_STATUS="OK"
    elif [ "$CI_FAILS" = "?" ]; then
      CI_STATUS="unknown"
    elif [ "$CI_FAILS" -gt 4 ] 2>/dev/null; then
      CI_STATUS="FAIL"
    else
      CI_STATUS="WARN"
    fi
    CI_NOTES="${CI_FAILS}/${CI_TOTAL} recent ci.yml runs failed"
  fi
fi
add "| CI health | ${CI_STATUS} | ${CI_NOTES} |"

# ── 2. Open issues & PRs ───────────────────────────────────────────────────

ISSUES_NOTES="gh unavailable"
PRS_NOTES="gh unavailable"
if gh_ready; then
  OPEN_ISSUES="$(gh_try issue list --repo "$REPO_SLUG" --state open --limit 200 \
    --json number --jq 'length' 2>/dev/null)"
  UNLABELLED="$(gh_try issue list --repo "$REPO_SLUG" --state open --limit 200 \
    --json number,labels --jq '[.[] | select(.labels | length == 0)] | length' 2>/dev/null)"
  [ -n "$OPEN_ISSUES" ] && ISSUES_NOTES="${OPEN_ISSUES} open, ${UNLABELLED:-?} unlabelled"
  OPEN_PRS="$(gh_try pr list --repo "$REPO_SLUG" --state open --limit 200 \
    --json number --jq 'length' 2>/dev/null)"
  DRAFT_PRS="$(gh_try pr list --repo "$REPO_SLUG" --state open --limit 200 \
    --json number,isDraft --jq '[.[] | select(.isDraft)] | length' 2>/dev/null)"
  [ -n "$OPEN_PRS" ] && PRS_NOTES="${OPEN_PRS} open, ${DRAFT_PRS:-?} draft"
fi
add "| Open issues | ${ISSUES_NOTES} | unlabelled issues need triage |"
add "| Open PRs | ${PRS_NOTES} | draft PRs may be stale |"

# ── 3. Dependency drift ────────────────────────────────────────────────────

dep_current() { grep "^$1 " gradle/libs.versions.toml 2>/dev/null | head -1 | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+' | head -1; }

FILAMENT_CUR="$(dep_current filament || true)"; FILAMENT_CUR="${FILAMENT_CUR:-unknown}"
KOTLIN_CUR="$(dep_current kotlin || true)"; KOTLIN_CUR="${KOTLIN_CUR:-unknown}"
ARCORE_CUR="$(grep '^arCore ' gradle/libs.versions.toml 2>/dev/null | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+' | head -1 || true)"
ARCORE_CUR="${ARCORE_CUR:-unknown}"

FILAMENT_LATEST="$(fetch https://api.github.com/repos/google/filament/releases/latest | jq -r '.tag_name // empty' 2>/dev/null | tr -d 'v')"
ARCORE_LATEST="$(fetch https://api.github.com/repos/google-ar/arcore-android-sdk/releases/latest | jq -r '.tag_name // empty' 2>/dev/null | tr -d 'v')"
KOTLIN_LATEST="$(fetch https://api.github.com/repos/JetBrains/kotlin/releases/latest | jq -r '.tag_name // empty' 2>/dev/null | tr -d 'v')"
FILAMENT_LATEST="${FILAMENT_LATEST:-unknown}"
ARCORE_LATEST="${ARCORE_LATEST:-unknown}"
KOTLIN_LATEST="${KOTLIN_LATEST:-unknown}"

DEP_OUTDATED=()
dep_row() { # name current latest
  if [ "$2" != "unknown" ] && [ "$3" != "unknown" ] && [ "$2" != "$3" ]; then
    DEP_OUTDATED+=("$1 $2 → $3")
  fi
}
dep_row Filament "$FILAMENT_CUR" "$FILAMENT_LATEST"
dep_row ARCore "$ARCORE_CUR" "$ARCORE_LATEST"
dep_row Kotlin "$KOTLIN_CUR" "$KOTLIN_LATEST"

if [ ${#DEP_OUTDATED[@]} -eq 0 ]; then
  DEP_STATUS="OK"; DEP_NOTES="Filament ${FILAMENT_CUR}, ARCore ${ARCORE_CUR}, Kotlin ${KOTLIN_CUR}"
else
  DEP_STATUS="OUTDATED"
  DEP_JOINED="$(IFS='|'; echo "${DEP_OUTDATED[*]}")"
  DEP_NOTES="${DEP_JOINED//|/; }"
fi
add "| Dependency drift | ${DEP_STATUS} | ${DEP_NOTES} |"

# ── 4. Version sync ────────────────────────────────────────────────────────

VERSION_STATUS="unknown"; VERSION_NOTES="sync-versions.sh not run"
if [ -x .claude/scripts/sync-versions.sh ]; then
  if bash .claude/scripts/sync-versions.sh >/tmp/_mr_sync.log 2>&1; then
    VERSION_STATUS="OK"; VERSION_NOTES="all version locations aligned"
  else
    VERSION_STATUS="FAIL"
    VERSION_NOTES="mismatch — run sync-versions.sh --fix"
  fi
fi
add "| Version sync | ${VERSION_STATUS} | ${VERSION_NOTES} |"

# ── 5. Quality signals: agent-skill drift ──────────────────────────────────

SKILL_STATUS="unknown"; SKILL_NOTES="check-sceneview-skill.sh not run"
if [ -x .claude/scripts/check-sceneview-skill.sh ]; then
  if bash .claude/scripts/check-sceneview-skill.sh >/tmp/_mr_skill.log 2>&1; then
    SKILL_STATUS="OK"; SKILL_NOTES="agents/sceneview/ in sync with library"
  else
    SKILL_STATUS="DRIFT"; SKILL_NOTES="agents/sceneview/ drift — see skill-drift job"
  fi
fi
add "| Agent skill drift | ${SKILL_STATUS} | ${SKILL_NOTES} |"

# ── 6. Release decision ────────────────────────────────────────────────────

REL_STATUS="unknown"; REL_NOTES="git tags unavailable"
LAST_TAG="$(git tag -l 'v*' 2>/dev/null | sort -V | tail -1)"
if [ -n "$LAST_TAG" ]; then
  COMMITS_SINCE="$(git rev-list --count "${LAST_TAG}..HEAD" 2>/dev/null || echo 0)"
  MEANINGFUL="$(git log "${LAST_TAG}..HEAD" --oneline 2>/dev/null \
    | grep -ivc 'chore\|docs\|ci\|style' || echo 0)"
  if [ "${MEANINGFUL:-0}" -ge 5 ] 2>/dev/null; then
    REL_STATUS="CONSIDER"
  else
    REL_STATUS="NO"
  fi
  REL_NOTES="${COMMITS_SINCE} commits since ${LAST_TAG} (${MEANINGFUL} meaningful)"
fi
add "| Release needed? | ${REL_STATUS} | ${REL_NOTES} |"

# ── footer ─────────────────────────────────────────────────────────────────

add ""
if [ ${#DEP_OUTDATED[@]} -gt 0 ]; then
  add "### Outdated dependencies"
  for d in "${DEP_OUTDATED[@]}"; do add "- $d"; done
  add ""
fi
add "<sub>Full action-taking sweep: run \`/maintain\` in a Claude Code session. "
add "Tracked by [#1303](https://github.com/${REPO_SLUG}/issues/1303).</sub>"

# ── emit ───────────────────────────────────────────────────────────────────

printf '%s' "$REPORT"

if [ -n "$OUT_FILE" ]; then
  printf '%s' "$REPORT" > "$OUT_FILE"
fi

if [ -n "${GITHUB_STEP_SUMMARY:-}" ]; then
  printf '%s' "$REPORT" >> "$GITHUB_STEP_SUMMARY"
fi

exit 0
