// Karma test-environment wiring for the sceneview-web jsTest suite.
//
// Why this exists
// ---------------
// `bindings/Filament.kt` is `@file:JsModule("filament") @file:JsNonModule`, and the
// test webpack config (`webpack.config.d/filament-polyfills.js`) maps that module to the
// global `Filament` via `config.externals`. In a real browser the Filament.js UMD script
// is loaded from a CDN before `sceneview-web.js`, so the global exists. The Karma /
// ChromeHeadless test page loads no such script, so the test bundle hits
// `Uncaught ReferenceError: Filament is not defined` at load time — before any test runs —
// which fails the ENTIRE jsTest suite (see issue #1401).
//
// The sceneview-web jsTest suite is pure-logic (camera math, GLB/config builders,
// AutoCenterGate / ContentCentering, version pin, WebXR constant checks) and never
// touches a live Filament/WebGL context. So a no-op `Filament` stub is enough to let the
// bundle load; the tests then run normally. Anything that genuinely needs a live GL
// context must guard/skip itself rather than rely on this stub.
//
// This file is appended to the Kotlin/JS-generated `karma.conf.js`. It serves a tiny
// bootstrap script (created on disk next to this config) and registers it as the FIRST
// entry in `config.files`, so `globalThis.Filament` is defined before the test bundle.
(function (config) {
    var path = require("path");
    var fs = require("fs");

    var bootstrapPath = path.join(__dirname, "filament-stub.bootstrap.generated.js");
    var bootstrapSource = [
        "// AUTO-GENERATED by karma.config.d/filament-stub.js — do not edit, do not commit.",
        "// Defines a no-op `Filament` global so the sceneview-web test bundle can load",
        "// in ChromeHeadless. See karma.config.d/filament-stub.js for the rationale (#1401).",
        "(function (g) {",
        "  if (typeof g.Filament === 'undefined') {",
        "    g.Filament = {",
        "      // Async asset loaders are no-ops: tests do not load real assets.",
        "      init: function (assets, onReady) { if (typeof onReady === 'function') onReady(); },",
        "      fetch: function (assets, onDone) { if (typeof onDone === 'function') onDone(); },",
        "      // Marker so a test can detect the stub and skip live-GL assertions.",
        "      __sceneviewTestStub: true",
        "    };",
        "  }",
        "})(typeof globalThis !== 'undefined' ? globalThis : (typeof window !== 'undefined' ? window : this));",
        ""
    ].join("\n");

    fs.writeFileSync(bootstrapPath, bootstrapSource);

    config.files = config.files || [];
    config.files.unshift({
        pattern: bootstrapPath,
        included: true,
        served: true,
        watched: false
    });
})(config);
